<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Banner extends Model
{
    protected $fillable = [
        'image',
        'title',
        'description',
        'status',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($banner) {
            if ($banner->image) {
                unlink($banner->image);
            }
        });
    }

    public static function createOrUpdateBanner($request, $bannerId = null)
    {
        return Banner::updateOrCreate(['id' => $bannerId], [
            'title'  => $request->title,
            'image'    => imageUpload($request->file('image'), 'banners', 'banner-', 600, 300, isset($bannerId) ? Banner::find($bannerId)->image : null),
            'description'  => $request->description,
            'status' => $request->status == 'on' ? 1 : 0,
        ]);
    }

//    public function district()
//    {
//        return $this->belongsTo(District::class);
//    }
}
