<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class District extends Model
{
    protected $fillable = [
        'district_name',
        'description',
        'status',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($district){
            if (count($district->areas))
            {
                $district->areas->each->delete();
            }
        });
    }

    public static function createOrUpdateDistrict($request, $districtId = null)
    {
        return District::updateOrCreate(['id' => $districtId], [
            'district_name'  => $request->district_name,
            'description'  => $request->description,
            'status' => $request->status == 'on' ? 1 : 0,
        ]);
    }

    public function areas()
    {
        return $this->hasMany(Area::class);
    }
}
